# Generated by Django 3.2.5 on 2021-07-20 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalTrials',
            fields=[
                ('cid', models.AutoField(primary_key=True, serialize=False)),
                ('source_name', models.CharField(blank=True, max_length=255, null=True)),
                ('source_id', models.IntegerField(blank=True, null=True)),
                ('title_kor', models.CharField(blank=True, max_length=255, null=True)),
                ('title_eng', models.TextField(blank=True, null=True)),
                ('recruitment_state', models.CharField(blank=True, max_length=255, null=True)),
                ('start_date', models.CharField(blank=True, max_length=255, null=True)),
                ('end_date', models.CharField(blank=True, max_length=255, null=True)),
                ('disease', models.TextField(blank=True, null=True)),
                ('disease_detail', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'db_table': 'clinical_trials',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Participate',
            fields=[
                ('pcid', models.AutoField(primary_key=True, serialize=False)),
                ('position', models.CharField(blank=True, max_length=255, null=True)),
                ('source_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'participate',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('name_kor', models.CharField(blank=True, max_length=255, null=True)),
                ('belong', models.CharField(blank=True, max_length=255, null=True)),
                ('job', models.CharField(blank=True, max_length=255, null=True)),
                ('major', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'person',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Thesis',
            fields=[
                ('tid', models.AutoField(primary_key=True, serialize=False)),
                ('name_kor', models.CharField(blank=True, max_length=255, null=True)),
                ('belong', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('journal', models.TextField(blank=True, null=True)),
                ('publication_date', models.CharField(blank=True, max_length=255, null=True)),
                ('citation', models.CharField(blank=True, max_length=255, null=True)),
                ('coworker', models.TextField(blank=True, null=True)),
                ('journal_index', models.CharField(max_length=45, null=True)),
            ],
            options={
                'db_table': 'thesis',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Writes',
            fields=[
                ('wid', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'writes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('pid', models.OneToOneField(db_column='pid', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='doctor', serialize=False, to='search.person')),
                ('education', models.TextField(blank=True, null=True)),
                ('career', models.TextField(blank=True, null=True)),
                ('url', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'doctor',
                'managed': False,
            },
        ),
    ]
