# Generated by Django 3.2.5 on 2021-08-09 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=255, null=True)),
                ('name_kor', models.CharField(blank=True, max_length=1000, null=True)),
                ('name_eng', models.CharField(blank=True, max_length=1000, null=True)),
                ('rare', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'disease',
                'managed': False,
            },
        ),
    ]
