# Generated by Django 3.2.9 on 2021-11-28 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_disease'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorTotalDisease',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name_kor', models.CharField(blank=True, db_collation='utf8mb4_bin', max_length=45, null=True)),
                ('belong', models.CharField(blank=True, db_collation='utf8mb4_bin', max_length=45, null=True)),
                ('major', models.TextField(blank=True, db_collation='utf8mb4_bin', null=True)),
                ('paper_count', models.IntegerField(blank=True, null=True)),
                ('paper_impact', models.FloatField(blank=True, null=True)),
                ('paper_disease_all', models.TextField(blank=True, db_collation='utf8mb4_bin', null=True)),
                ('clinical_count', models.IntegerField(blank=True, null=True)),
                ('clinical_disease_all', models.TextField(blank=True, db_collation='utf8mb4_bin', null=True)),
                ('img', models.TextField(blank=True, db_collation='utf8mb4_bin', null=True)),
            ],
            options={
                'db_table': 'doctor_total_disease',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Totaldisease',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('disease_code', models.TextField(blank=True, null=True)),
                ('disease_kor', models.TextField(blank=True, null=True)),
                ('disease_eng', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'totaldisease',
                'managed': False,
            },
        ),
    ]
