# Generated by Django 3.2.5 on 2022-01-21 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_doctortotaldisease_totaldisease'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorAllscore',
            fields=[
                ('belong_name', models.CharField(db_collation='utf8_general_ci', max_length=255, primary_key=True, serialize=False)),
                ('disease', models.TextField(blank=True, db_collation='utf8_general_ci', null=True)),
            ],
            options={
                'db_table': 'doctor_allscore',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NodeCris',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('label', models.TextField(blank=True, null=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('shape', models.TextField(blank=True, null=True)),
                ('color', models.TextField(blank=True, null=True)),
                ('size', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'node_cris',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NodeCrisCnt',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('fromit', models.IntegerField(blank=True, null=True)),
                ('toit', models.IntegerField(blank=True, null=True)),
                ('width', models.FloatField(blank=True, null=True)),
                ('title', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'node_cris_cnt',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SnPaper',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('label', models.TextField(blank=True, null=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('shape', models.TextField(blank=True, null=True)),
                ('color', models.TextField(blank=True, null=True)),
                ('size', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'SN_paper',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SnPaper50',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('label', models.TextField(blank=True, null=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('shape', models.TextField(blank=True, null=True)),
                ('color', models.TextField(blank=True, null=True)),
                ('size', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'SN_paper50',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SnPaperCnt',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('fromit', models.IntegerField(blank=True, null=True)),
                ('toit', models.IntegerField(blank=True, null=True)),
                ('width', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'SN_paper_cnt',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SnPaperCnt50',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('fromit', models.IntegerField(blank=True, null=True)),
                ('toit', models.IntegerField(blank=True, null=True)),
                ('width', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'SN_paper_cnt50',
                'managed': False,
            },
        ),
    ]
