# Generated by Django 3.2.5 on 2022-02-08 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0005_doctorall_doctorall2_partpaperedge_partpapernode_snpaperedgeyear'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorAll3',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name_kor', models.CharField(blank=True, db_collation='utf8_general_ci', max_length=45, null=True)),
                ('belong', models.CharField(blank=True, db_collation='utf8_general_ci', max_length=45, null=True)),
                ('major', models.TextField(blank=True, db_collation='utf8mb4_general_ci', null=True)),
                ('education', models.TextField(blank=True, db_collation='utf8mb4_general_ci', null=True)),
                ('career', models.TextField(blank=True, db_collation='utf8mb4_general_ci', null=True)),
                ('img', models.TextField(blank=True, db_collation='utf8mb4_general_ci', null=True)),
                ('link', models.TextField(blank=True, db_collation='utf8mb4_general_ci', null=True)),
                ('hospital_code', models.TextField(blank=True, db_collation='utf8mb4_general_ci', null=True)),
                ('disease', models.TextField(blank=True, db_collation='utf8_general_ci', null=True)),
                ('a', models.TextField(blank=True, db_collation='latin1_swedish_ci', db_column='A', null=True)),
                ('b', models.TextField(blank=True, db_collation='latin1_swedish_ci', db_column='B', null=True)),
                ('c', models.TextField(blank=True, db_collation='latin1_swedish_ci', db_column='C', null=True)),
                ('d', models.TextField(blank=True, db_collation='latin1_swedish_ci', db_column='D', null=True)),
                ('e', models.TextField(blank=True, db_collation='latin1_swedish_ci', db_column='E', null=True)),
                ('f', models.TextField(blank=True, db_collation='latin1_swedish_ci', db_column='F', null=True)),
                ('g', models.TextField(blank=True, db_collation='latin1_swedish_ci', db_column='G', null=True)),
                ('h', models.TextField(blank=True, db_collation='latin1_swedish_ci', db_column='H', null=True)),
                ('i', models.TextField(blank=True, db_collation='latin1_swedish_ci', db_column='I', null=True)),
                ('j', models.TextField(blank=True, db_collation='latin1_swedish_ci', db_column='J', null=True)),
                ('k', models.TextField(blank=True, db_collation='latin1_swedish_ci', db_column='K', null=True)),
                ('l', models.TextField(blank=True, db_collation='latin1_swedish_ci', db_column='L', null=True)),
                ('m', models.TextField(blank=True, db_collation='latin1_swedish_ci', db_column='M', null=True)),
                ('n', models.TextField(blank=True, db_collation='latin1_swedish_ci', db_column='N', null=True)),
                ('o', models.TextField(blank=True, db_collation='latin1_swedish_ci', db_column='O', null=True)),
                ('p', models.TextField(blank=True, db_collation='latin1_swedish_ci', db_column='P', null=True)),
                ('q', models.TextField(blank=True, db_collation='latin1_swedish_ci', db_column='Q', null=True)),
                ('r', models.TextField(blank=True, db_collation='latin1_swedish_ci', db_column='R', null=True)),
                ('s', models.TextField(blank=True, db_collation='latin1_swedish_ci', db_column='S', null=True)),
                ('t', models.TextField(blank=True, db_collation='latin1_swedish_ci', db_column='T', null=True)),
                ('u', models.TextField(blank=True, db_collation='latin1_swedish_ci', db_column='U', null=True)),
                ('v', models.TextField(blank=True, db_collation='latin1_swedish_ci', db_column='V', null=True)),
                ('w', models.TextField(blank=True, db_collation='latin1_swedish_ci', db_column='W', null=True)),
                ('x', models.TextField(blank=True, db_collation='latin1_swedish_ci', db_column='X', null=True)),
                ('y', models.TextField(blank=True, db_collation='latin1_swedish_ci', db_column='Y', null=True)),
                ('z', models.TextField(blank=True, db_collation='latin1_swedish_ci', db_column='Z', null=True)),
                ('paper_count', models.IntegerField(blank=True, null=True)),
                ('paper_impact', models.FloatField(blank=True, null=True)),
                ('clinical_count', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'doctor_all3',
                'managed': False,
            },
        ),
    ]
