# Generated by Django 3.2.5 on 2022-02-10 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0006_doctorall3'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrisEdge',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('fromit', models.IntegerField(blank=True, null=True)),
                ('toit', models.IntegerField(blank=True, null=True)),
                ('cnt', models.IntegerField(blank=True, null=True)),
                ('title', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cris_edge',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nodes',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('label', models.TextField(blank=True, null=True)),
                ('disease', models.TextField(blank=True, null=True)),
                ('color', models.TextField(blank=True, null=True)),
                ('paper_cnt', models.IntegerField(blank=True, null=True)),
                ('clinical_cnt', models.IntegerField(blank=True, null=True)),
                ('belong', models.TextField(blank=True, null=True)),
                ('borderwidth', models.IntegerField(blank=True, db_column='borderWidth', null=True)),
            ],
            options={
                'db_table': 'Nodes',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='DoctorAll3',
        ),
        migrations.DeleteModel(
            name='PartPaperEdge',
        ),
        migrations.DeleteModel(
            name='PartPaperNode',
        ),
        migrations.DeleteModel(
            name='SnPaper50',
        ),
        migrations.DeleteModel(
            name='SnPaperCnt50',
        ),
    ]
